### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by Eoghan1232** [k8snetworkplumbingwg/cni-log#1]
Shall we create an initial release of this project?

**Comment by maiqueb** [comment]
+1; I'd release a `v0.1.0` version.

**Comment by adrianchiris** [comment]
Hey, any update on doing a first release ?

id like to use this to add some logging to https://github.com/k8snetworkplumbingwg/accelerated-bridge-cni  :)

**Comment by Eoghan1232** [comment]
Hey @adrianchiris , agreed. 
let's get #5 #6 #7 merged for security fixes and then we can create a release :)
if you give a quick review, we can merge it today and look to release today/tomorrow.

**Comment by adrianchiris** [comment]
cool thanks !

**Comment by adrianchiris** [comment]
CNI log was released. this one can be closed @Eoghan1232
