### ISSUE TITLE
Ordering of debug and verbose

### ISSUE THREAD

**Issue by andreaskaris** [k8snetworkplumbingwg/cni-log#10]
It's currently :

5 | debug | DebugLevel
-- | -- | --
6 | verbose | VerboseLevel

Shouldn't it be :

5 | verbose | VerboseLevel
-- | -- | --
6 | debug | DebugLevel

Or, should "verbose" better be called "trace"?

5 | debug | DebugLevel
-- | -- | --
6 | trace | TraceLevel

That's very subjective but I have never seen any place where "verbose" logged more info than "debug"

**Comment by Eoghan1232** [comment]
@andreaskaris this is good to close now too right?

**Comment by andreaskaris** [comment]
@Eoghan1232  actually no. I did not touch this. "verbose" is still more verbose than "debug". If it's a deliberate design choice then I do not want to interfere with that. What do you think about the naming of the log levels?

**Comment by Eoghan1232** [comment]
@andreaskaris gotcha.

it's generally implementation dependent, but the convention of where "debug" provides more details than "verbose" is fine with me. 
I am also okay with using "trace", as it will follow same conventions as other logging libraries. 

so this would be the new order:
1. PanicLevel
2. ErrorLevel
3. WarningLevel
4. InfoLevel
5. DebugLevel
6. TraceLevel

**Comment by andreaskaris** [comment]
Assuming this is the correct dependency for cri-o's logs, they only have 5 log levels:
https://github.com/cri-o/cri-o/blob/main/internal/log/log.go

1. Fatalf
2. Errorf
3. Warnf
4. Infof
5. Debugf

So I suppose that's why Verbosef was added below Debugf. I'd personally prefer your last comment with 6. TraceLevel, but I really don't want to blow this out of proportion. Given that there's no standard, it must be documented anyway. So it's your call, either close out the issue and stick with the current API or go with 6. TraceLevel

**Comment by Eoghan1232** [comment]
Hi @andreaskaris , we discussed this in the community. 

decision is to remove the verbose, and have Debug as the highest. 
This would be the order:

PanicLevel
ErrorLevel
WarningLevel
InfoLevel
DebugLevel

TraceLevel could be added at a later point if it was needed.

**Comment by andreaskaris** [comment]
@Eoghan1232 I can volunteer to do that, wdyt

**Comment by Eoghan1232** [comment]
sure if you have the time ! :) 
Thanks @andreaskaris !
