### ISSUE TITLE
cni-log always creates the default log file in /var/log/cni-log.log

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/cni-log#8]
An application using it would most likely set its own path via `SetLogFile` before logging any messages.
currently we end up with the default log file always being created even if logs are not written to it.

proposal:
remove default log file, force user to set it

alternative:
if log file path was not set, use default (initialize on first write)

**Comment by Eoghan1232** [comment]
#9 fixes this.
